[package]
name = "privacypass_http"
version = "0.1.0"
authors = ["gpestana <g6pestana@gmail.com>"]
edition = "2018"

[dependencies]
htokens-rs = { path = "../../" } 
reqwest = {version = "0.11.5", features = ["blocking", "json"]}
serde = "1.0.130"
serde_json = "1.0.68"
bincode = "1.3.3"
